# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

# specific path build
trigger:
  paths:
    include:
    - src/Azure/Java/*

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  runTests: 'false'
  subscription: 'Free Trial (767058f0-43e0-45da-a32e-ba7ee09e4846)'

stages:

- stage: BuildJava
  jobs:
  - job: BuildAndPublishJava
    steps:

    - task: Maven@3
      inputs:
        mavenPomFile: 'src\Azure\Java\pom.xml'
        mavenOptions: '-Xmx3072m'
        javaHomeOption: 'JDKVersion'
        jdkVersionOption: '1.11'
        jdkArchitectureOption: 'x64'
        publishJUnitResults: false
        testResultsFiles: '**/TEST-*.xml'
        goals: 'package'
    - task: CopyFiles@2
      displayName: Copy java Files variables
      inputs:
        SourceFolder: $(system.defaultworkingdirectory)/src/azure/java/target/azure-functions/
        Contents: '**'
        TargetFolder: $(Build.ArtifactStagingDirectory)/java   

    - task: PublishBuildArtifacts@1
      displayName: Publish java Artifact from $(Build.ArtifactStagingDirectory)
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)/java'
        ArtifactName: 'java'
        # publishLocation: 'Container'
          

- stage: DeployJavaFunction
  dependsOn: "BuildJava"
  jobs:
  - job: DeployFunctions 
    condition: and(succeeded(), eq(variables['Build.Reason'], 'Manual'))
    steps:

    - task: DownloadPipelineArtifact@2
      displayName: download the artifact

    - task: AzureFunctionApp@1
      displayName: Azure Function App deploy java windows
      inputs:
        azureSubscription: '$(subscription)'
        appType: 'functionApp'
        appName: 'func-BenchMark-Sample-Win-Java'
        package: "$(Pipeline.Workspace)/java/CloudRepublic.BenchMark.Java"
        deploymentMethod: "auto"

    - task: AzureFunctionApp@1
      displayName: Azure Function App deploy java Linux
      inputs:
        azureSubscription: '$(subscription)'
        appType: 'functionAppLinux'
        appName: 'func-BenchMark-Sample-Lin-Java'
        package: "$(Pipeline.Workspace)/java/CloudRepublic.BenchMark.Java"
        deploymentMethod: "auto"