# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Build and release website

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  buildApi:
    name: Build API
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore --configuration "RELEASE"
    - name: Test
      run: dotnet test --no-build --verbosity normal --configuration "RELEASE"
    - name: Publish
      run: dotnet publish ./src/API/CloudRepublic.BenchMark.API --output ./outputs/api --configuration "RELEASE"
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.1
      with:
        name: api
        path: ./outputs/api

  buildTestRunner:
    name: Build Test Runner
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore --configuration "RELEASE"
    - name: Test
      run: dotnet test --no-build --verbosity normal --configuration "RELEASE"
    - name: Publish
      run: dotnet publish ./src/Orchestrator/CloudRepublic.BenchMark.Orchestrator --output ./outputs/testRunner --configuration "RELEASE"
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.1
      with:
        name: testRunner
        path: ./outputs/testRunner

  deploy:
    name: deploy application
    runs-on: ubuntu-latest
    needs: ["buildApi", "buildTestRunner"]
    steps:
      # Checkout code
    - uses: actions/checkout@v3

      # Log into Azure
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Deploy Bicep file
    - name: deploy
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
        resourceGroupName: ${{ secrets.AZURE_RG }}
        template: .Deployment/deployment.bicep
        parameters: prefix=${{ secrets.DEPLOYMENT_PREFIX }}
        failOnStdErr: false
